### PR TITLE
Use passed-in eventloop when acquiring RedisConnectionPool

### LINKED ISSUE #180: Precondition failed in Redis 4.1.0 when using repository pattern
### Describe the bug

After updating to 4.1.0 the following error is thrown as soon as I use my cacheRepo.
```
[ ERROR ] Abort.401: UserModel not authenticated. [request-id: 0661DE6F-B71E-41D6-9B06-2BB4A3F92F9B]
Precondition failed: file .../NIO/ChannelPipeline.swift, line 1447
2021-01-30 15:24:10.165750+0100 Run[13873:207019] Precondition failed: file .../NIO/ChannelPipeline.swift, line 1447
```
The execution gets stuck at:
```swift
    /// Checks the necessary condition of currently running on the called `EventLoop` for making forward progress.
    @inlinable
    public func preconditionInEventLoop(file: StaticString = #file, line: UInt = #line) {
        precondition(self.inEventLoop, file: file, line: line)
    }
```
Routes without cacheRepo usage, are not affected. Downgrading to redis 4.0.0 shows no errors and everything works as expected.

Inside `configure.swift` redis is setup using:
```swift
    let redisHostname = Environment.get("REDIS_HOSTNAME") ?? "localhost"
    let redisPort: Int
    let redisPassword = Environment.get("REDIS_PASSWORD")
    if (app.environment == .testing) {
        if let testPort = Environment.get("REDIS_PORT_TEST") {
            redisPort = Int(testPort) ?? 6380
        } else {
            redisPort = 6380
        }
    } else {
        redisPort = 6379
    }
    app.redis.configuration = try .init(hostname: redisHostname, port: redisPort, password: redisPassword)
    
    // specify what repository will be created by cacheRepoFactory
    app.cacheRepoFactory.use { req in
        RedisRepo(client: req.redis)
    }
    app.cacheRepoFactory.useForApp { app in
        RedisRepo(client: app.redis)
    }
```
RedisRepo contains just the requirements from the cacheRepo protocol:
```swift
struct RedisRepo: CacheRepo {
    let client: RedisClient
    
    // MARK: - JSON Storage
    
    func save<E>(key: String, to entity: E) -> EventLoopFuture<Void> where E: Encodable {
        let redisKey = RedisKey(key)
        do {
            return client.set(redisKey, to: try JSONEncoder().encode(entity), onCondition: .none, expiration: .keepExisting)
                .transform(to: ())
        } catch {
            return client.eventLoop.makeFailedFuture(error)
        }
    }
    ...
```
CacheRepoFactory contains:
```swift
protocol CacheRepo: ABACCacheRepo {
    func save<E>(key: String, to entity: E) -> EventLoopFuture<Void> where E: Encodable
    func save<E>(key: String, to entity: E, expirationInSeconds seconds: Int) -> EventLoopFuture<Void> where E: Encodable
    func get<D>(key: String, as type: D.Type) -> EventLoopFuture<D?> where D: Decodable
    func getExistingKeys<D>(using keys: [String], as type: [D].Type) -> EventLoopFuture<[D]> where D: Decodable
    func setExpiration(forKey key: String, afterSeconds seconds: Int) -> EventLoopFuture<Bool>
    func delete(key: String) -> EventLoopFuture<Int>
    func delete(keys: [String]) -> EventLoopFuture<Int>
    func timeToLive(key: String) -> EventLoopFuture<Int>
    func exists(_ keys: String...) -> EventLoopFuture<Int>
    func exists(_ keys: [String]) -> EventLoopFuture<Int>
    // hash storage
    func getHash<D>(key: String, field: String, as type: D.Type) -> EventLoopFuture<D?> where D: Decodable
    func getHashAll<D>(key: String, as type: D.Type) -> EventLoopFuture<[String:D]> where D: Decodable
    func setHash<E>(_ key: String, field: String, to entity: E) -> EventLoopFuture<Bool> where E: Encodable
    func setMHash<E>(_ key: String, items: Dictionary<String, E>) -> EventLoopFuture<Void> where E: Encodable
    func deleteHash(_ key: String, fields: String...) -> EventLoopFuture<Int>
    func deleteHash(_ key: String, fields: [String]) -> EventLoopFuture<Int>
}
 
 
 
struct CacheRepoFactory {
    // CacheRepo in Request
    var make: ((Request) -> CacheRepo)?
    mutating func use(_ make: @escaping ((Request) -> CacheRepo)) {
        self.make = make
    }
    
    // CacheRepo in Application
    var makeForApp: ((Application) -> CacheRepo)?
    mutating func useForApp(_ make: @escaping ((Application) -> CacheRepo)) {
        self.makeForApp = make
    }
}
 
 
 
extension Application {
    private struct CacheRepoKey: StorageKey {
        typealias Value = CacheRepoFactory
    }
 
    var cacheRepoFactory: CacheRepoFactory {
        get {
            self.storage[CacheRepoKey.self] ?? .init()
        }
        set {
            self.storage[CacheRepoKey.self] = newValue
        }
    }
}
 
 
 
extension Application {
    var cacheRepo: CacheRepo {
        self.cacheRepoFactory.makeForApp!(self)
    }
}
 
extension Request {
    var cacheRepo: CacheRepo {
        self.application.cacheRepoFactory.make!(self)
    }
}
```

### To Reproduce

First I encountered the error after `request.cacheRepo.get(...)` was used. But it actually happens on all repo methods. As soon as you try to `return request.eventLoop...`
```swift
struct UserModelBearerAuthenticator: BearerAuthenticator {

    struct AccessDataKey: StorageKey {
        typealias Value = AccessData
    }
    
    func authenticate(bearer: BearerAuthorization, for request: Request) -> EventLoopFuture<Void> {
        return request.cacheRepo.get(key: bearer.token, as: AccessData.self).flatMap { accessData in
            guard let accessData = accessData else {
                return request.eventLoop.makeSucceededFuture(())
            }
            ...
```

1. Add redis 4.1.0 package
2. Create repository and factory (see code snippets above)
2. Use whatever cacheRepo method you want in a route handler, afterwards every  return of a future (`req.eventLoop.`) will throw an error
3. See error

### Expected behavior

No error, same behaviour like in redis 4.0.0.

### Environment

* Vapor Framework version: 4.39.2
* Vapor Toolbox version: 18.3.0
* OS version: MacOS Catalina 10.15.7

### PR DESCRIPTION
**Pull request by siemensikkema**
Use the passed-in eventloop when acquiring RedisConnectionPool to prevent triggering a precondition related to ending up in a wrong eventloop (fixes #180, replaces: #183).

### CODE REVIEW

**Comment by siemensikkema** [comment]
@danramteke @Mordil this is a quick drive-by PR that _possibly_ fixes the issues reported in 4.1.0. Am I on the right course?

File: Sources/Redis/Application+Redis.swift [hunk 1]
```diff
@@ -3,7 +3,7 @@ import Vapor
 extension Application {
     public struct Redis {
         func pool(for eventLoop: EventLoop) -> RedisConnectionPool {
-            self.application.redisStorage.pool(for: self.eventLoop.next(), id: self.id)
+            self.application.redisStorage.pool(for: eventLoop, id: self.id)
```
Comment (Mordil) [inline Sources/Redis/Application+Redis.swift:6]: I'd like to dig more into why this is broken now vs. before - I did a diff comparison and this is how it worked before #178 - but if unit tests pass and people are reporting it fixes it.. then I guess we can merge. Worst case is we're in the same situation

**Review by Mordil — APPROVED** [review]

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by tanner0101** [comment]
These changes are now available in [4.1.1](https://github.com/vapor/redis/releases/tag/4.1.1)

File: Sources/Redis/Application+Redis.swift (hunk 1 above)
Comment (danramteke) [reply Sources/Redis/Application+Redis.swift:6]: Yeah, I made sure to preserve the existing logic. Glad this change helps!
